version: "3.8"
services:
  thift:
    image: thrift-app
    ports:
      - 5000:5000
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    depends_on:
      - db
    networks: [ "thrift" ]
  db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: midepeter
   ports:
     - 5432:5432
   networks: [ "thrift" ]
networks:
  thrift:
    driver: bridge
